export const INCREMENT_BREAK = 'INCREMENT_BREAK';
export const DECREMENT_BREAK = 'DECREMENT_BREAK';

export const INCREMENT_SESSION = 'INCREMENT_SESSION';
export const DECREMENT_SESSION = 'DECREMENT_SESSION';

export const INCREASE_BY_ONE = 'INCREASE_BY_ONE';
export const DECREASE_BY_ONE = 'DECREASE_BY_ONE';

export const RESET = 'RESET';
