// Break
export const INCREMENT_BREAK = 'INCREMENT_BREAK';
export const DECREMENT_BREAK = 'DECREMENT_BREAK';

// Session
export const INCREMENT_SESSION = 'INCREMENT_SESSION';
export const DECREMENT_SESSION = 'DECREMENT_SESSION';

// Timer
export const INCREASE_ONE_MINUTE = 'INCREASE_ONE_MINUTE';
export const DECREASE_ONE_MINUTE = 'DECREASE_ONE_MINUTE';
export const DECREASE_ONE_SECOND = 'DECREASE_ONE_SECOND';
export const RESET_SECONDS = 'RESET_SECONDS';
export const RESET = 'RESET';
export const SET_IS_RUNNING = 'SET_IS_RUNNING';
export const SET_BREAK_TIME = 'SET_BREAK_TIME';
